### ISSUE TITLE
Library fails

### ISSUE THREAD

**Issue by DrTron** [mgaggero/Adafruit_Python_HTU21D#1]
Hello,

I'm trying to use your library with my Raspberry Pi and my HTU21D sensor. The sensor works, I have found a small test program written in c that outputs measurements. Still, I'd like to use something a bit easier.

Running your simpletest.py (after installing the library) gives me:

Traceback (most recent call last):
  File "./simpletest.py", line 46, in <module>
    print 'Temp = {0:0.2f} *C'.format(sensor.read_temperature())
  File "build/bdist.linux-armv7l/egg/Adafruit_HTU21D/HTU21D.py", line 78, in read_temperature
  File "build/bdist.linux-armv7l/egg/Adafruit_HTU21D/HTU21D.py", line 58, in read_raw_temp
  File "build/bdist.linux-armv7l/egg/Adafruit_GPIO/I2C.py", line 129, in readList
IOError: [Errno 5] Input/output error

I'm a bit confused as the build/bdist.linux-armv7/-directory is empty, even though the install went fine....

**Comment by mgaggero** [comment]
Fixed in 43ae28adc789097d48f53162e0708be897aa6f18.
